services:
  mysql:
    image: mysql:8.0
    container_name: task-engine-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskdb
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./task.sql:/docker-entrypoint-initdb.d/task.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "taskuser",
          "-ptaskpassword",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Mock API service for task execution
  mock-api:
    build:
      context: ./mock-api
    container_name: task-engine-mock-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - TASK_SUCCESS_RATE=0.9 # 90% of tasks succeed
      - MIN_PROCESSING_TIME_MS=100
      - MAX_PROCESSING_TIME_MS=2000
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Task engine service
  task-engine:
    build:
      context: .
    container_name: task-engine
    depends_on:
      mysql:
        condition: service_healthy
      mock-api:
        condition: service_healthy
    ports:
      - "9090:9090" # Metrics endpoint
    environment:
      - DB_CONNECTION_STRING=taskuser:taskpassword@tcp(mysql:3306)/taskdb?parseTime=true&timeout=5s&readTimeout=5s&writeTimeout=5s&clientFoundRows=true&maxAllowedPacket=4194304&interpolateParams=true
      - API_ENDPOINT=http://mock-api:3000
      - MAX_CONCURRENT=50
      - TASK_BUFFER_SIZE=600
      - MAX_QUERY_BATCH_SIZE=200
      - BUFFER_REFILL_THRESHOLD=0.5
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9090/health",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: task-engine-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    depends_on:
      task-engine:
        condition: service_healthy

  grafana:
    image: grafana/grafana:9.0.0
    container_name: task-engine-grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes:
  mysql-data:
  prometheus-data:
  grafana-data:
