version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: task-processor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskdb
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./task.sql:/docker-entrypoint-initdb.d/task.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "taskuser",
          "-ptaskpassword",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
