global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "task-engine"
    scrape_interval: 5s
    static_configs:
      - targets: ["task-engine:9090"]

  - job_name: "mysql"
    scrape_interval: 5s
    static_configs:
      - targets: ["mysqld-exporter:9104"]
